# Generated by Django 5.1.3 on 2024-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0008_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', '쉬움'), ('Medium', '중간'), ('Hard', '어려움')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problems/'),
        ),
    ]
