# Generated by Django 5.1.3 on 2024-12-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0009_alter_problem_difficulty_alter_problem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='options',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
    ]
