# Generated by Django 5.1.3 on 2024-12-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0011_problem_example_input_problem_example_output'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='기본 내용 없음')),
                ('category', models.CharField(blank=True, choices=[('알고리즘', '알고리즘'), ('자료구조', '자료구조'), ('프로그래밍 언어', '프로그래밍 언어'), ('기타', '기타')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('알고리즘', '알고리즘'), ('자료구조', '자료구조'), ('프로그래밍 언어', '프로그래밍 언어'), ('기타', '기타')], max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('쉬움', '쉬움'), ('보통', '보통'), ('어려움', '어려움')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
