# Generated by Django 5.1.3 on 2024-12-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0012_data_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='contest_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='problem_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(choices=[('public', '전체공개'), ('private', '나만 보기')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
