# Generated by Django 5.1.3 on 2024-12-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0015_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
