# Generated by Django 5.1.3 on 2024-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0018_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='completed_members',
        ),
        migrations.AddField(
            model_name='mission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
