# Generated by Django 5.1.3 on 2024-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0019_remove_mission_completed_members_mission_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='solved_problems',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
